from .tasks import txt_context_summarize
from enum import Enum
def context_summarize(taxonomy,llm_query):
  """
  Function to get context
  
  Args:
  taxonomy - (list[str]): taxonomy generated by 'taxonomy' function
  llm_query - (function): function to answer NLP questions (like LLM API)
  """
  taxonomy_txt = '@TAXONOMY: ' + taxonomy
  text = taxonomy_txt + "\n\n===\n" + txt_context_summarize
  output = llm_query(text)[0]
  return output

class methods(Enum):
  SUMMARIZE=0

def context(taxonomy,llm_qurery,method=methods.SUMMARIZE):
    if methods.SUMMARIZE==method:
        return context_summarize(taxonomy,llm_qurery)
    else:
        raise ValueError("context's method is invalid")